# docs.serverless.com

service: lambda-probot

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  webpackIncludeModules: true

provider:
  name: aws
  runtime: nodejs6.10

  environment:
    WEBHOOK_SECRET: ${env:WEBHOOK_SECRET}
    APP_ID: ${env:APP_ID}
    TRELLO_API_KEY: ${env:TRELLO_API_KEY}
    TRELLO_DEV_TOKEN: ${env:TRELLO_DEV_TOKEN}
    TRELLO_CARD_ID: ${env:TRELLO_CARD_ID}
    GITHUB_OWNER: ${env:GITHUB_OWNER}
    GITHUB_REPO: ${env:GITHUB_REPO}

#    variable1: value1

#  exclude:
#    - exclude-me.js
#    - exclude-me-dir/**

functions:
  probot:
    handler: handler.autoResponder
    events:
     - http:
         path: probot
         method: post

  createReport:
    handler: handler.createReport
    events:
     - schedule: rate(1 day)

# you can add CloudFormation resource templates here
#resources:
#  Resources:
#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: my-new-bucket
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"