# docs.serverless.com

service: lambda-probot

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  webpackIncludeModules: true

provider:
  name: aws
  runtime: nodejs6.10

# you can define service wide environment variables here
#  environment:
#    variable1: value1

#  exclude:
#    - exclude-me.js
#    - exclude-me-dir/**

functions:
  probot:
    handler: handler.autoResponder

    # Define function environment variables here
    environment:
      WEBHOOK_SECRET: ${env:WEBHOOK_SECRET}
      APP_ID: ${env:APP_ID}
      TRELLO_API_KEY: ${env:TRELLO_API_KEY}
      TRELLO_DEV_TOKEN: ${env:TRELLO_DEV_TOKEN}
      TRELLO_CARD_ID: ${env:TRELLO_CARD_ID}

    events:
     - http:
         path: probot
         method: post

# you can add CloudFormation resource templates here
#resources:
#  Resources:
#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: my-new-bucket
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"